{
	"version": 1616010124,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/nitrogenpump-sheet0.png",
		"images/shield-sheet0.png",
		"images/tomatando-sheet0.png",
		"images/warplanepump-sheet0.png",
		"images/enemy5-sheet0.png",
		"images/warplanepumpparticle.png",
		"images/enemy2-sheet0.png",
		"images/enemy1-sheet0.png",
		"images/enemy3-sheet0.png",
		"images/enemy3-sheet1.png",
		"images/enemygunge-sheet0.png",
		"images/enemy4-sheet0.png",
		"images/enemy4-sheet1.png",
		"images/enemy4-sheet2.png",
		"images/enemy51-sheet0.png",
		"images/anyobject-sheet0.png",
		"images/newgame-sheet0.png",
		"images/loadinggame-sheet0.png",
		"images/settings-sheet0.png",
		"images/exit-sheet0.png",
		"images/credits-sheet0.png",
		"images/levellevelbottom-sheet0.png",
		"images/transição1-sheet0.png",
		"images/door-sheet0.png",
		"images/alavanca-sheet0.png",
		"images/alavanca-sheet1.png",
		"images/alavanca2-sheet0.png",
		"images/alavanca2-sheet1.png",
		"images/passagem-sheet0.png",
		"images/door5-sheet0.png",
		"images/door7-sheet0.png",
		"images/perigo1.png",
		"images/perigo21-sheet0.png",
		"images/perigo27-sheet0.png",
		"images/perigo27-sheet1.png",
		"images/perigobala-sheet0.png",
		"images/chracterimage-sheet0.png",
		"images/chracterimage-sheet1.png",
		"images/chracterimage-sheet2.png",
		"images/collisions.png",
		"images/chracterbullet-sheet0.png",
		"images/chracterhitbox-sheet0.png",
		"images/powerupparticles.png",
		"images/powerupparticles2.png",
		"images/chractershield-sheet0.png",
		"images/powerupparticles3.png",
		"images/enemyblublu-sheet0.png",
		"images/checkpoint-sheet0.png",
		"images/menubotton-sheet0.png",
		"images/bt-sheet0.png",
		"images/hpbar.png",
		"images/sadicon-sheet0.png",
		"images/backbottom-sheet0.png",
		"images/npc1-sheet0.png",
		"images/interagir.png",
		"images/interação-sheet0.png",
		"images/level1-sheet0.png",
		"images/level2-sheet0.png",
		"images/level3-sheet0.png",
		"images/sensor1-sheet0.png",
		"images/sensor2-sheet0.png",
		"images/sensor3-sheet0.png",
		"images/pausescreen.png",
		"images/efeitossonoros-sheet0.png",
		"images/efeitossonoros-sheet1.png",
		"images/loadingbar-sheet0.png",
		"images/loadingbar-sheet1.png",
		"images/loadingbar-sheet2.png",
		"images/background.png",
		"images/intoxicaçãoeffect.png",
		"images/enenmy4particles.png",
		"images/tower-sheet0.png",
		"images/a-sheet0.png",
		"images/fakeplattaform.png",
		"images/plataform-sheet0.png",
		"images/nada-sheet0.png",
		"images/catapult-sheet0.png",
		"images/catapultsensor-sheet0.png",
		"images/reliquia-sheet0.png",
		"images/bossfight-sheet0.png",
		"images/bossfight-sheet1.png",
		"images/bossfight-sheet2.png",
		"images/fakewall-sheet0.png",
		"images/sensorfw-sheet0.png",
		"images/bfsensor-sheet0.png",
		"images/uniãodasreliquias-sheet0.png",
		"images/uniãodasreliquias-sheet1.png",
		"images/barracontaminhação.png",
		"images/progressão-sheet0.png",
		"images/objetodetransição-sheet0.png",
		"images/objetodetransição-sheet1.png",
		"images/livro-sheet0.png",
		"images/splashempresa-sheet0.png",
		"images/splashjogo-sheet0.png",
		"images/mousesensor-sheet0.png",
		"images/cutscene-sheet0.png",
		"images/arvore1-sheet0.png",
		"images/minhoca-sheet0.png",
		"images/abellha-sheet0.png",
		"images/dialogoabelha-sheet0.png",
		"media/alavanca 3.ogg",
		"media/passagem.ogg",
		"media/coletando artefato.ogg",
		"media/jumpland.m4a",
		"media/jumpland.ogg",
		"media/save point.ogg",
		"media/sfx_step_grass_r.m4a",
		"media/sfx_step_grass_r.ogg",
		"media/flaunch.m4a",
		"media/flaunch.ogg",
		"media/dano 3.ogg",
		"media/botão clicado.m4a",
		"media/botão clicado.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/livro aberto.ogg",
		"media/musica do jogo (online-audio-converter.com).m4a",
		"media/musica do jogo (online-audio-converter.com).ogg",
		"media/musica das telas.m4a",
		"media/musica das telas.ogg",
		"media/bossfight musica.m4a",
		"media/bossfight musica.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"penumbra.png",
		"pathfind.js"
	]
}